### DISCUSSION TITLE
Dark mode support

### DISCUSSION THREAD

**Discussion by ritchiemarkov** [OpenGIS/Waymark#34] [Ideas]
Hello Joe! 

Crazy idea, but maybe some one find it usefull - Can we change tiles provider with our theme state? 

I think its a nice touch (i dont seen anyone doing it) to trigger a tiles style in accordance with our preference. 

Have a great day!

**Comment by morehawes** [comment]
> Crazy idea

Often the best! ;)

> Can we change tiles provider with our theme state?

Are you suggesting that you could specify a "dark" Basemap and a "light" Basemap which would be displayed upon the users dark/light mode preference? This is an interesting idea :)

I definitely plan on better dark mode support in the future. I recently used the following CSS to "invert" the Waymark UI colours for better integration [a dark Basemap](https://www.thunderforest.com/maps/transport-dark/) that worked quite well:

```css
/* Map Dark */
.leaflet-popup-pane,
.leaflet-tooltip-pane,
.leaflet-control-fullscreen,
.leaflet-control-locate,
.leaflet-control-layers,
.leaflet-control-zoom a {
	filter: invert(100%);
}
.waymark-container .waymark-elevation .waymark-elevation-close,
.leaflet-popup-pane .waymark-type-text,
.leaflet-control-layers .waymark-type-text {
	filter: invert(100%);
}
.waymark-map-container.waymark-is-viewer ul.waymark-info li.waymark-info-image_large_url a {
	filter: invert(100%);
}
```
